version: "2"
services:
  app:
    build: ./app
    links:
      - db
    ports:
      - "8100:8100"
    volumes:
      - ./app:/app
  db:
    image: mysql:5.7
#    ports:
#      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ritsoftv4-pass
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
